import Link from 'next/link';
import { ArrowUpRight, ArrowRight, HeartHandshake, Clock3, MessageCircle, MapPin, Phone, Sparkles, ShieldCheck, Smile } from 'lucide-react';
export default function Home() {
 return <main id="main">
 <section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> YOUR NEIGHBORHOOD DENTIST IN ARVADA</p><h1>Dentistry you can<br/>feel <em>good</em> about.</h1><p className="hero-description">A familiar face. A gentler approach. And the time to care for you as a person.</p><p className="hero-detail">Thoughtful family dentistry with Dr. Jeffrey Moser.<br/>Right here in Arvada, Colorado.</p><div className="actions"><a className="button" href="tel:+13036579006">Call to schedule <ArrowUpRight size={18}/></a><Link className="text-link" href="/about">Meet Dr. Moser <ArrowRight size={17}/></Link></div><div className="hero-trust"><div className="trust-mark"><HeartHandshake size={25} strokeWidth={1.4}/></div><div><strong>A little more personal. A lot more caring.</strong><span>New patients, and familiar faces, welcome.</span></div></div></div><div className="hero-visual"><div className="landscape"><img src="/colorado.jpg" alt="Golden evening light across Colorado foothills and open grassland" fetchPriority="high"/><div className="image-shade"/><div className="image-caption"><MapPin size={15}/> ROOTED IN COLORADO. FOCUSED ON YOU.</div></div><div className="photo-note"><span className="note-icon"><HeartHandshake size={26} strokeWidth={1.3}/></span><div>Your comfort comes first.<small>Always time for a conversation.</small></div><span className="note-star">✳</span></div></div></section>
 <section className="values wrap" aria-label="Our approach"><div><Clock3/><div><h3>Care without the rush</h3><p>Time to talk. Space to ask questions.</p></div></div><div><HeartHandshake/><div><h3>A gentle, human approach</h3><p>Your comfort is part of your care.</p></div></div><div><MessageCircle/><div><h3>Clarity at every step</h3><p>Understand your options. Feel at ease.</p></div></div></section>
 <section className="care-section wrap"><div className="section-heading"><div><p className="eyebrow">GOOD CARE. EVERYDAY CONFIDENCE.</p><h2>For your smile.<br/><em>For your life.</em></h2></div><div><p>From a routine check-in to a tooth that needs attention, start with a conversation and a plan that makes sense for you.</p><Link className="text-link" href="/services">Explore our care <ArrowRight size={17}/></Link></div></div><div className="service-grid">{[{icon:ShieldCheck,title:'Preventive care',text:'A healthy foundation for the years ahead.',id:'preventive',number:'01'},{icon:Sparkles,title:'Restorative care',text:'Thoughtful care for teeth that need a little help.',id:'restorative',number:'02'},{icon:Smile,title:'Family dentistry',text:'A familiar dental home, through life’s changes.',id:'family',number:'03'}].map(({icon:Icon,title,text,id,number})=><Link href={`/services#${id}`} className="service-card" key={id}><div className="service-top"><Icon size={32} strokeWidth={1.25}/><span>{number}</span></div><h3>{title}</h3><p>{text}</p><span className="circle-arrow"><ArrowUpRight size={19}/></span></Link>)}</div></section>
 <section className="doctor-section"><div className="wrap doctor-grid"><div className="doctor-monogram" aria-label="Dr. Jeffrey Moser, Doctor of Dental Surgery"><span className="eyebrow">CARING FAMILY DENTISTRY</span><div className="monogram">JM<span>DDS</span></div><p>Experience in dentistry.<br/>A personal connection.</p><span className="monogram-bottom">JEFFREY C. MOSER, DDS · ARVADA, CO</span></div><div className="doctor-copy"><p className="eyebrow">MEET DR. JEFFREY MOSER</p><h2>A dentist who<br/>takes the time<br/><em>to know you.</em></h2><p>Good dentistry begins with a good conversation. Dr. Moser is a University of Iowa–trained general dentist whose patients describe him as gentle, thorough, and easy to talk to.</p><p>That personal connection is at the heart of Caring Family Dentistry. A place to ask questions, feel heard, and take the next step with confidence.</p><Link className="text-link" href="/about">Get to know Dr. Moser <ArrowRight size={18}/></Link></div></div></section>
 <section className="reassurance wrap"><p className="eyebrow">YOU CAN START RIGHT HERE</p><h2>Been a while?<br/><em>That’s okay.</em></h2><p>Whether it’s been six months or several years, you deserve to feel comfortable taking the next step. Tell us what’s on your mind. We’ll take it from there, together.</p><Link className="button" href="/new-patients">Your first visit <ArrowUpRight size={18}/></Link><div className="reassurance-aside"><HeartHandshake size={37} strokeWidth={1.2}/><span>No pressure to have<br/>all the answers.</span></div></section>
 <section className="patient-section"><div className="wrap"><p className="eyebrow">THE THINGS THAT MATTER</p><h2>Care that people <em>remember.</em></h2><p className="patient-intro">Patients describe more than their dental care. They describe how it feels to be listened to.</p><div className="patient-words"><span>Gentle.</span><span>Thorough.</span><span>Easy to talk to.</span></div><p className="patient-summary">A little kindness and a real conversation can change how a dental visit feels.</p></div></section>
 <section className="visit-section wrap"><div><p className="eyebrow">A FAMILIAR PLACE, CLOSE TO HOME</p><h2>Your next chapter<br/>starts with <em>hello.</em></h2><p>We’d love to help you feel at home here.</p><a className="button" href="tel:+13036579006"><Phone size={17}/> (303) 657-9006 <ArrowUpRight size={18}/></a></div><div className="visit-details"><MapPin size={27} strokeWidth={1.4}/><h3>Caring Family Dentistry</h3><p>7578 Sheridan Blvd<br/>Arvada, CO 80003</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Caring+Family+Dentistry+7578+Sheridan+Blvd+Arvada+CO+80003" target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={17}/></a><div className="hours-note">Please call for current office hours and appointment availability.</div></div></section>
 </main>
}
